project:
  type: website
  output-dir: docs

website:
  title: "Metadata Inventory"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lsheble/metadata_inventory

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css



