project:
  type: website
  output-dir: docs

website:
  title: "Metadata Inventory"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lsheble/metadata_inventory

format:
  html:
    theme: cosmo
#      light: cosmo
#      dark: slate  low visibility for DT tables with dark them as currently configured
    css: styles.css
    page-layout: full



